# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require File.expand_path('../app/models/*.rb', __FILE__)

Rails.application.load_tasks

namespace :country do 
 desc "effect population wealth"
 task  :work do
  Pry.start(binding)
 end
end